version: "3.7"

services:
    postgres:
        image: postgres
        container_name: gamershub_db
        volumes:
            - gamershub-data:/var/lib/postgresql/data
        ports:
            - "5430:5432"
        environment:
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=secret
            - POSTGRES_DB=gamershub

    # frontend:
    #     build:
    #         dockerfile: Dockerfile
    #         context: ./frontend
    #     image: gamershub_frontend
    #     container_name: gamershub_frontend
    #     volumes:
    #         - ./frontend:/app
    #     ports:
    #         - 8081:8080
    #     env_file: ./frontend/.env
    #     command: npm run serve
    #     depends_on:
    #         - backend

    backend:
        build: 
            dockerfile: Dockerfile
            context: ./backend
        image: gamershub_backend
        container_name: gamershub_backend
        volumes:
            - ./backend:/app
        ports:
            - 3001:3000
        env_file: ./backend/.env
        depends_on:
            - postgres

volumes:
    gamershub-data:
        driver: local